---
- name: Sending email using Ansible
  hosts: localhost
  connection: local
  tasks:
    - name: mail 
      mail:
        host: smtp.gmail.com
        port: 587
        username: "username@gmail.com"
        password: "email password"
        to: John Sam <johnsam12@gmail.com>
        subject: Ansible-report
        body: 'System {{ ansible_hostname }} has been successfully provisioned.'
      delegate_to: localhost
